dICP:
  parameters:
    tanh_steepness: 5.0   # Steepness of tanh function for weighting
    target_pad_val: 1000  # Value to pad target with for batch composition, 
                          # want this large enough to never get computed as 
                          # nearest neighbour for source
    const_iter: False     # If true, force a constant number of iterations as defined by max_iter
  
  
  functionality:
    gumbel: False        # If true, use Gumbel-Softmax trick for nearest neighour
  # Not yet implemented
  #  svd: False           # If true, use SVD to solve pt2pt problem, no effect for pt2pl

  logging:
    verbose: False              # If true, print out more information
    matched_ratio_thresh: 0.1   # Only count points with a weight above this threshold as matched