dICP:
  parameters:
    tanh_steepness: 5.0
    const_iter: True  # If true, force a constant number of iterations as defined by max_iter
  
  functionality:
    sparse: True
    svd: False  # If true, use SVD to solve pt2pt problem, no effect for pt2pl

  logging:
    verbose: False